version: '3'

services:
  postgres:
    image: postgres
    ports:
     - "5432:5432"

  pgweb:
    image: sosedoff/pgweb
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    ports:
     - "8081:8081"
    depends_on:
      - postgres
